name: Deploy Static Website

on:
  push:
    branches: [main] # or your main branch
 

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check pwd
        run: pwd
